"""initial_tables

Revision ID: 19c3d33ce457
Revises:
Create Date: 2026-04-18 00:16:00.561623

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "19c3d33ce457"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
